### ISSUE TITLE
Create Flutter Project

### ISSUE THREAD

**Issue by jhalljhall** [bluegrass-devs/hopehelpstrength#1]

**Comment by joeblankenship1** [comment]
I'll go ahead and close this unless you need me to keep it open.

**Comment by borsezf2** [comment]
is there anything needed to be done?

**Comment by joeblankenship1** [comment]
Quite a bit actually. We're meeting tomorrow morning at Awesome Inc in Lexington if you're in the area. Otherwise, we'll be refining the requirements and prioritizing features so that people can just build to what is posted in the Projects tab of this repo.
Is there something that you wanted to contribute?

**Comment by borsezf2** [comment]
i'm from india but would love to work on a interesting project.
Hope your meeting finalize some good changes.
once it's done.
i would like to have a look at them and if it's possible i would contribute too

**Comment by joeblankenship1** [comment]
See the Projects tab for project details and Issues for problems/requests.
